/**
 * Fresh directory seed (2026-08): Ollama ≥250K pulls / ~6mo + current closed flagships.
 * Prefer undisclosed over guesses. Facts drawn from Ollama library pages / lab docs.
 */
import type { ModelFacts } from "./types.js";

const TODAY = "2026-08-07";
const CREDITS = {
  generated_with: "https://modelfacts.dev",
  built_by: "Catalyst Forge — https://www.catalystforge.com/",
};

function base(
  partial: Omit<ModelFacts, "model_facts_version" | "generated" | "credits" | "status"> & {
    status?: ModelFacts["status"];
  },
): ModelFacts {
  return {
    model_facts_version: "0.1.0",
    status: "active",
    ...partial,
    generated: { date: TODAY, generator: "directory seed — Ollama/API refresh 2026-08" },
    credits: CREDITS,
  };
}

export const seedCatalog: Record<string, ModelFacts> = {
  "google-gemma-4-31b": base({
    name: "Gemma-4-31B",
    developer: "Google DeepMind",
    license: "Gemma Terms of Use",
    homepage: "https://ollama.com/library/gemma4",
    weights: "https://ollama.com/library/gemma4",
    architecture: {
      type: "dense transformer (decoder-only)",
      parameters: "31B",
      context_window: "256k",
      quantization: "GGUF (Ollama default)",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (Gemma 4 instruct + thinking modes)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Representative dense 31B from Gemma 4 family (also E2B/E4B/12B/26B-MoE)",
    },
    safety: {
      refusal_sensitivity: "high",
      instruction_following: "high",
      filter_type: "hybrid",
    },
    benchmarks: [
      { name: "MMLU Pro", score: 85.2 },
      { name: "GPQA Diamond", score: 84.3 },
      { name: "LiveCodeBench v6", score: 80.0 },
    ],
  }),

  "qwen-qwen3.5-35b": base({
    name: "Qwen3.5-35B",
    developer: "Alibaba (Qwen)",
    license: "Apache-2.0",
    homepage: "https://ollama.com/library/qwen3.5",
    weights: "https://ollama.com/library/qwen3.5",
    architecture: {
      type: "dense transformer (decoder-only)",
      parameters: "35B",
      context_window: "256k",
      quantization: "GGUF (Ollama default)",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (Qwen3.5 multimodal family)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Representative mid-size from Qwen3.5 family (0.8B–122B on Ollama)",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "qwen-qwen3.6-35b": base({
    name: "Qwen3.6-35B",
    developer: "Alibaba (Qwen)",
    license: "Apache-2.0",
    homepage: "https://ollama.com/library/qwen3.6",
    weights: "https://ollama.com/library/qwen3.6",
    architecture: {
      type: "dense transformer (decoder-only)",
      parameters: "35B",
      context_window: "256k",
      quantization: "GGUF (Ollama default)",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (open-weight Qwen3.6; thinking preservation)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Agentic coding focus; 27B and 35B tags on Ollama",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "nvidia-nemotron-3-super": base({
    name: "Nemotron-3-Super",
    developer: "NVIDIA",
    license: "NVIDIA Open Model License",
    homepage: "https://ollama.com/library/nemotron-3-super",
    weights: "https://ollama.com/library/nemotron-3-super",
    architecture: {
      type: "mixture of experts (MoE)",
      parameters: "120B",
      active_parameters: "12B",
      context_window: "undisclosed",
      quantization: "GGUF / cloud (Ollama)",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (multi-agent / high-throughput reasoning)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "120B MoE activating ~12B per token",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "zai-glm-5.1": base({
    name: "GLM-5.1",
    developer: "Z.ai",
    license: "MIT",
    homepage: "https://ollama.com/library/glm-5.1",
    weights: "https://ollama.com/library/glm-5.1",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "198k",
      quantization: "cloud / Ollama",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (agentic engineering post-training)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Long-horizon agentic coding flagship (pre-5.2)",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
    benchmarks: [{ name: "SWE-Bench Pro", score: 58.4 }],
  }),

  "minimax-m2.7": base({
    name: "MiniMax-M2.7",
    developer: "MiniMax",
    license: "UNKNOWN",
    homepage: "https://ollama.com/library/minimax-m2.7",
    weights: "https://ollama.com/library/minimax-m2.7",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "undisclosed",
      quantization: "cloud / Ollama",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (coding / agentic M2 series)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "liquid-lfm2": base({
    name: "LFM2-24B-A2B",
    developer: "Liquid AI",
    license: "UNKNOWN",
    homepage: "https://ollama.com/library/lfm2",
    weights: "https://ollama.com/library/lfm2",
    architecture: {
      type: "hybrid / MoE (on-device family)",
      parameters: "24B",
      active_parameters: "2B",
      context_window: "undisclosed",
      quantization: "GGUF (Ollama default)",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (on-device / edge tool-calling)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "medium",
      coding: "medium",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Largest LFM2 variant on Ollama (24B total, ~2B active)",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "nvidia-nemotron-3-nano-omni": base({
    name: "Nemotron-3-Nano-Omni",
    developer: "NVIDIA",
    license: "NVIDIA Open Model License",
    homepage: "https://ollama.com/library/nemotron3",
    weights: "https://ollama.com/library/nemotron3",
    architecture: {
      type: "dense transformer (multimodal)",
      parameters: "33B",
      context_window: "undisclosed",
      quantization: "GGUF (Ollama default)",
      modalities_in: ["text", "image", "audio", "video"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (omni multimodal enterprise workflows)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "medium",
      vision_input: "enabled",
      audio_input: "enabled",
      tool_use: "native",
      notes: "Unified video/audio/image/text understanding",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "moonshot-kimi-k2.6": base({
    name: "Kimi-K2.6",
    developer: "Moonshot AI",
    license: "UNKNOWN",
    homepage: "https://ollama.com/library/kimi-k2.6",
    weights: "https://ollama.com/library/kimi-k2.6",
    architecture: {
      type: "undisclosed (native multimodal agentic)",
      parameters: "undisclosed",
      context_window: "undisclosed",
      quantization: "cloud / Ollama",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (long-horizon coding / agent orchestration)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "minimax-m3": base({
    name: "MiniMax-M3",
    developer: "MiniMax",
    license: "UNKNOWN",
    homepage: "https://ollama.com/library/minimax-m3",
    weights: "https://ollama.com/library/minimax-m3",
    architecture: {
      type: "undisclosed (native multimodal)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "cloud / Ollama",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (coding & agentic frontier)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "1M context; native multimodality per Ollama listing",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "ornith-35b": base({
    name: "Ornith-35B",
    developer: "Ornith",
    license: "UNKNOWN",
    homepage: "https://ollama.com/library/ornith",
    weights: "https://ollama.com/library/ornith",
    architecture: {
      type: "dense transformer (decoder-only)",
      parameters: "35B",
      context_window: "undisclosed",
      quantization: "GGUF (Ollama default)",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (self-improving open family for agentic coding)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Representative 35B from Ornith family (also 9B)",
    },
    safety: {
      refusal_sensitivity: "low",
      instruction_following: "high",
      filter_type: "raw",
    },
  }),

  "deepseek-v4-flash": base({
    name: "DeepSeek-V4-Flash",
    developer: "DeepSeek",
    license: "MIT",
    homepage: "https://ollama.com/library/deepseek-v4-flash",
    weights: "https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash",
    architecture: {
      type: "mixture of experts (MoE)",
      parameters: "284B",
      active_parameters: "13B",
      context_window: "1M",
      quantization: "bf16 / cloud (Ollama)",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (V4 series; no/thinking/max thinking modes)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Efficient 1M-context MoE preview of DeepSeek-V4",
    },
    safety: {
      refusal_sensitivity: "low",
      instruction_following: "high",
      filter_type: "raw",
    },
    benchmarks: [
      { name: "MMLU-Pro", score: 86.4, notes: "V4-Flash High" },
      { name: "GPQA Diamond", score: 87.4, notes: "V4-Flash High" },
      { name: "SWE Verified", score: 78.6, notes: "V4-Flash High" },
    ],
  }),

  "ibm-granite-4.1": base({
    name: "Granite-4.1",
    developer: "IBM",
    license: "Apache-2.0",
    homepage: "https://ollama.com/library/granite4.1",
    weights: "https://ollama.com/library/granite4.1",
    architecture: {
      type: "dense transformer (decoder-only)",
      parameters: "8B",
      context_window: "undisclosed",
      quantization: "GGUF (Ollama default)",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (enterprise Granite 4.1 family: 3B/8B/30B)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "medium",
      coding: "high",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Representative 8B from Granite 4.1; multilingual + RAG/tool use",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),

  "deepseek-v4-pro": base({
    name: "DeepSeek-V4-Pro",
    developer: "DeepSeek",
    license: "MIT",
    homepage: "https://ollama.com/library/deepseek-v4-pro",
    weights: "https://ollama.com/library/deepseek-v4-pro",
    architecture: {
      type: "mixture of experts (MoE)",
      parameters: "1.6T",
      active_parameters: "49B",
      context_window: "1M",
      quantization: "bf16 / cloud (Ollama)",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (V4 flagship; no/thinking/max thinking modes)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Frontier V4 MoE — 1.6T total / 49B active",
    },
    safety: {
      refusal_sensitivity: "low",
      instruction_following: "high",
      filter_type: "raw",
    },
    benchmarks: [
      { name: "MMLU-Pro", score: 87.5, notes: "V4-Pro Max" },
      { name: "GPQA Diamond", score: 90.1, notes: "V4-Pro Max" },
      { name: "SWE Verified", score: 80.6, notes: "V4-Pro Max" },
    ],
  }),

  "mistral-medium-3.5": base({
    name: "Mistral-Medium-3.5",
    developer: "Mistral AI",
    license: "Modified MIT",
    homepage: "https://ollama.com/library/mistral-medium-3.5",
    weights: "https://huggingface.co/mistralai/Mistral-Medium-3.5-128B",
    architecture: {
      type: "dense transformer (decoder-only)",
      parameters: "128B",
      context_window: "256k",
      quantization: "bf16 / GGUF",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (unified instruct + reasoning + coding weights)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      languages: "dozens of languages including EN/FR/ES/DE/IT/PT/NL/ZH/JA/KO/AR",
      notes: "Configurable reasoning effort; replaces Medium 3.1 / Magistral / Devstral 2 in products",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
    benchmarks: [{ name: "SWE-Bench Verified", score: 77.6 }],
  }),

  "zai-glm-5.2": base({
    name: "GLM-5.2",
    developer: "Z.ai",
    license: "MIT",
    homepage: "https://ollama.com/library/glm-5.2",
    weights: "https://ollama.com/library/glm-5.2",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "cloud / Ollama",
      modalities_in: ["text"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (long-horizon coding-agent post-training)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "disabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "1M usable context; High/Max thinking effort levels",
    },
    safety: {
      refusal_sensitivity: "medium",
      instruction_following: "high",
      filter_type: "hybrid",
    },
    benchmarks: [
      { name: "Terminal-Bench 2.1", score: 81.0 },
      { name: "SWE-bench Pro", score: 62.1 },
    ],
  }),

  // —— Closed API flagships (Aug 2026) ——
  "openai-gpt-5.6-sol": base({
    name: "GPT-5.6 Sol",
    developer: "OpenAI",
    license: "Proprietary (API)",
    release_date: "2026-07-09",
    homepage: "https://openai.com/",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "undisclosed",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "GPT-5.6 flagship tier (Sol); Terra/Luna are lower tiers",
    },
    safety: {
      refusal_sensitivity: "high",
      instruction_following: "high",
      filter_type: "censored",
    },
  }),

  "openai-gpt-5.6-luna": base({
    name: "GPT-5.6 Luna",
    developer: "OpenAI",
    license: "Proprietary (API)",
    release_date: "2026-07-09",
    homepage: "https://openai.com/",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "undisclosed",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Fast/cheap GPT-5.6 tier for high-volume work",
    },
    safety: {
      refusal_sensitivity: "high",
      instruction_following: "high",
      filter_type: "censored",
    },
  }),

  "anthropic-claude-fable-5": base({
    name: "Claude Fable 5",
    developer: "Anthropic",
    license: "Proprietary (API)",
    release_date: "2026-06-09",
    homepage: "https://www.anthropic.com/",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "undisclosed",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (Constitutional AI / RLHF lineage)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Top Claude 5 tier above Opus for hardest long-horizon work",
    },
    safety: {
      refusal_sensitivity: "high",
      instruction_following: "high",
      filter_type: "censored",
    },
  }),

  "anthropic-claude-opus-5": base({
    name: "Claude Opus 5",
    developer: "Anthropic",
    license: "Proprietary (API)",
    release_date: "2026-07-24",
    homepage: "https://www.anthropic.com/",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "undisclosed",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (Constitutional AI / RLHF lineage)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Upper-mid Claude 5 tier; strong coding/agentic default",
    },
    safety: {
      refusal_sensitivity: "high",
      instruction_following: "high",
      filter_type: "censored",
    },
  }),

  "anthropic-claude-sonnet-5": base({
    name: "Claude Sonnet 5",
    developer: "Anthropic",
    license: "Proprietary (API)",
    release_date: "2026-06-30",
    homepage: "https://www.anthropic.com/",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "undisclosed",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed (Constitutional AI / RLHF lineage)",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "Mid Claude 5 tier — volume coding / general workhorse",
    },
    safety: {
      refusal_sensitivity: "high",
      instruction_following: "high",
      filter_type: "censored",
    },
  }),

  "google-gemini-3.1-pro": base({
    name: "Gemini 3.1 Pro",
    developer: "Google DeepMind",
    license: "Proprietary (API)",
    homepage: "https://deepmind.google/models/gemini/",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "undisclosed",
      modalities_in: ["text", "image", "audio", "video"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "enabled",
      tool_use: "native",
      notes: "Multimodal Pro-tier Gemini 3.x; accuracy / research oriented",
    },
    safety: {
      refusal_sensitivity: "high",
      instruction_following: "high",
      filter_type: "censored",
    },
  }),

  "google-gemini-3.6-flash": base({
    name: "Gemini 3.6 Flash",
    developer: "Google DeepMind",
    license: "Proprietary (API)",
    release_date: "2026-07-21",
    homepage: "https://deepmind.google/models/gemini/",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "1M",
      quantization: "undisclosed",
      modalities_in: ["text", "image", "audio", "video"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "enabled",
      tool_use: "native",
      notes: "Flash-tier Gemini 3.6 workhorse (Jul 2026)",
    },
    safety: {
      refusal_sensitivity: "high",
      instruction_following: "high",
      filter_type: "censored",
    },
  }),

  "xai-grok-4.5": base({
    name: "Grok 4.5",
    developer: "xAI",
    license: "Proprietary (API)",
    homepage: "https://x.ai/",
    architecture: {
      type: "undisclosed (transformer-family)",
      parameters: "undisclosed",
      context_window: "500k",
      quantization: "undisclosed",
      modalities_in: ["text", "image"],
      modalities_out: ["text"],
    },
    training: {
      knowledge_cutoff: "undisclosed",
      methodology: "undisclosed",
      tokens: "undisclosed",
    },
    capabilities: {
      natural_language: "full",
      reasoning_math: "high",
      coding: "high",
      vision_input: "enabled",
      audio_input: "disabled",
      tool_use: "native",
      notes: "xAI cheap-flagship tier; real-time X data integration claimed",
    },
    safety: {
      refusal_sensitivity: "low",
      instruction_following: "high",
      filter_type: "hybrid",
    },
  }),
};
